### ISSUE TITLE
Getting errors when trying you cart

### ISSUE THREAD

**Issue by phillipmadsen** [drehimself/laravel-shopping-cart-example#1]
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Gloudemans\Shoppingcart\Cart::search() must be an instance of Closure, array given, called in /home/vagrant/bbb/ecom/app/Http/Contr
ollers/WishlistController.php on line 32 in /home/vagrant/bbb/ecom/vendor/gloudemans/shoppingcart/src/Cart.php:286

**Comment by drehimself** [comment]
Looks like the shopping cart package has had a major update. I'm assuming you are using that newer version. I'll eventually update to it, but for now if you continue to use `"gloudemans/shoppingcart": "~1.3"` in your composer.json, it should work:

Here's an issue to update their documentation: https://github.com/Crinsane/LaravelShoppingcart/issues/159
